Builtins/builtins.h
Memory/Reference_Counter.h
README.md

I developed some classes as utilities

Changes for improvement of Reference counter, builtin utilities and exceptition

---

Builtins/builtins.h
CodeGen/writeBytecodes.h
Parser/parser.h

The parser generates a class of the imported code due to this the class inside it becomes inaccessible so to solve this i made switched to namespace whose name can also be changed.

IMPORT Statement

---

Parser/parser.h

import with full path solved

---

AST/ast.h

providing the concept of classes

Introduce classes

---

Parser/parser.h

for if, else, while, for, elif.

Update parser.h in order to handle other block based exprs

---

IR/builtins.h

collection of homogen elements similar to vectors in C++

Introducting lists

---

AST/ast.h
AST/visitor.h
Parser/parser.h

I have added some features with the help of them we are able to use type annotations on functions and vardecl and classes for OOP.
Example:
```
class myclass:
a:i32 = 1
def sum(b = i32{}):
return a + b
```

Classes, TypeAnnotation

---

AST/ast.h
AST/visitor.h
Parser/parser.h

In most of the OOP languages there is a concept of methods so to make Csq more robust and productive i have developed that feature and now it's available.

Support for Methods

---

AST/ast.h
Parser/parser.h
Runtime/core.h
Tokenizer/tokenizer.h

The older version of language was having collections but they were homeogeneous but as the newer version is dynamically typed so now it allows linear heterogeneous collections
like:
```
a := {1,2,3,4,'hello'}
a[0]
a[4]
```

1D heterogeneous collection

---

AST/ast.h
AST/visitor.h

I am added the CollectionUpdateNode and COLLECTION_UPDATE in the AST which should fix the issue.

Solution for Error #136

---

AST/ast.h
AST/visitor.h
Builtin/basic.h
Parser/parser.h
Runtime/core.h
Tokenizer/tokenizer.h

After somedays of improvement i have sucessfully made functions which are inspired from older syntax but have some modifications
like:
Simple function to sum
```
def sum(x,y)
return x+y
```
Calling:
```
print sum(2,4)
```

Functions in Csq4.2

---

AST/ast.h
AST/visitor.h
Parser/parser.h
csq.cpp

Now to make Csq4.2 more usable i introduced module importing.
It's syntax is:
```
import <modulename>
Ex:
import mod
```

Importing of code 

---

Runtime/core.h

I have written certain benchmark codes and found a shocking surprise
Csq code:
```
i := 0
while i < 5000:
i = i+1
```
Python code:
```
i = 0
while i < 5000:
i = i+1
```
THe results were:
Csq took 159ms
Python took 71ms
I then searched for the code decreasing speed and try to optimize it and now the results are:
Csq took 13ms
Python took 61ms

Improving performance

---

Tokenizer/tokenizer.h

token.token = val;
now this statement  use only one time

tokenizer check function update 

---

Runtime/core.h
Runtime/memory.h

Now Csq will be able to handle collections more efficiently.

Collections update

---

Grammar/grammer.py
Parser/parser.py
Tokenizer/tokenizer.py
main.py

I updated tokenize function to tokenize strings as well as indents.

String Tokenizer

---

.gitignore
AST/ast.py
Compiletime/error.py
Parser/parser.py

Csq Python Update
Compile Time Errors
(for compile time error i make other folder )
Cimport 
and some improvements

Csq Python Update

---

AST/ast.py
Parser/parser.py

Now compile function correctly parse nodes like VarAssign and VarDecl.

Parser Base Created

---

Tokenizer/tokenizer.py

Update tokenizer.py Solution 

---

AST/ast.py
Parser/parser.py
Tokenizer/tokenizer.py

Now the parser can parse simple control flow statements like if, elif and else.

Parser Improvement

---

AST/ast.py
Compiletime/error.py
Grammar/grammar.py
Parser/parser.py
README.md
Runtime/code_format.py
Tokenizer/tokenizer.py
main.py
pyformatter.py

* Make sure that your code work properly.
* After writing your code you should commit it.
* Don't commit two different things together.
* After commit code you should run **pyformatter.py** it will formate your code. (this step only for python code )
* Make sure that you code works after formateing. 
* After all things push your code to our **main branch**.

formatting python code

---

Compiletime/syntax_check.py
Parser/parser.py
Tokenizer/tokenizer.py

We are doing parsing but what we will do if someone has miswritten the syntax so syntax error for sure, but to do that we should have a seperate file verifying each type of statement with it's grammar.

Introducing Syntax_check file to check for valid grammar

---

csq.cpp

Before the code fully migrate to python, I have fixed issue #160

Break out of the loop if file doesn't exist

---

Compiletime/syntax_check.py
Parser/parser.py

The grammar checker for variable decl and assignment.

Grammar checker applied on VarAssign

---

Compiletime/syntax_check.py
Parser/parser.py
Tokenizer/tokenizer.py
pyformatter.py

Short code 
Comments add
formate python code

Update Tokenizer and formated code

---

Compiletime/wrapper.py
csq.py

I sucessfully made csq.py operational and now it's able to produce c++ code.

Csq.py is now working

---

csq.py

#185 Issue Solved

---

.editorconfig
Compiletime/syntax_check.py
Compiletime/wrapper.py
Makefile
Parser/parser.py
README.md
_doc.py
csq.py
setup.cfg

The checker currently uses pycodestyle only.
I have yet to look at other alternatives that can work better

Add doc checker

---

AST/ast.py
Grammar/grammar.py
Parser/parser.py
csq.py

I have done certain new changes to solve #187 and i have checked and ran some test cases i found it works.

Fixed issue #187

---

AST/ast.py
Parser/parser.py

I found the acute reason why indents were creating trouble.
Now i hope issue #185 is solved.

Solution for issue of indents

---

AST/ast.py
Builtin/basic.h
csq.py

Compiling issue solved

---

Builtin/basic.h
Runtime/core.h
Runtime/memory.h

To implement OOPs firstly i have modified runtime files so that it can be used.

OOP's Runtime base

---

.gitignore
AST/ast.py
Compiletime/error.py
Compiletime/syntax_check.py
Compiletime/wrapper.py
Grammar/grammar.py
Parser/parser.py
Runtime/code_format.py
Tokenizer/tokenizer.py
csq.py

This update focuses on code refinement, enhancing clarity, and streamlining maintainability. It includes simplification and readability enhancements, making it easier for contributors to collaborate and maintain the project.

Improved Code Clarity and Maintainability

---

AST/ast.py
Parser/parser.py

Solution for func arg issue

---

Builtin/basic.h
Parser/parser.py
Runtime/eval.h
Runtime/memory.h

I have done some increments due to which now one more datatype has born (int).

Int datatype

---

Compiler/AST/ast.py
Compiler/Parser/parser.py
Core/Builtin/codes.h
Core/Runtime/core.h

```
class myclass:
a := 50
obj := object('myclass')
print obj.a
```

member vars in class

---

Compiler/Parser/parser.py

Remade of #239 
For error #232

Error list

---

Compiler/AST/ast.py
Compiler/Parser/parser.py

#229 More updated version where not only cimport but also import statement is fixed.

Cimport and Import statement file path issue solved

---

Compiler/AST/ast.py
Compiler/Parser/parser.py
Core/Builtin/basic.h
Core/Runtime/class.h
Core/Runtime/core.h
Core/Runtime/memory.h
csq.py

Some changes made to resolve bugs found.
Errors solved
#252 #251

U15 patch1

---

Compiler/AST/ast.py
Compiler/Compiletime/wrapper.py
Compiler/Parser/parser.py
Core/Builtin/basic.h
Core/Builtin/codes.h
Core/Runtime/core.h
Core/Runtime/error.h
Core/Runtime/eval.h
Core/Runtime/memory.h
Core/Runtime/object.h
README.md
csq.py

Speed and Memory Improvement

---

Core/Include/Import/list.csq
Core/Include/Import/math.csq

Introduced : List and Math module.

Introducing some basic builtin functionalities

---

Compiler/Grammar/grammar.py

Changed grammar so that we can use emoji and symbols to represent variables
like :
```
π := 3.1415
print π
```

Adding emoji and mathematical symbols as identifiers

---

Compiler/Grammar/grammar.py
Compiler/Tokenizer/tokenizer.py
Core/Builtin/basic.h
Core/Include/Cimport/cos.cpp
Core/Include/Cimport/csv.cpp
Core/Include/Cimport/fileio.cpp
Core/Include/Cimport/plot.cpp
build.sh

* Added cos.cpp cpp module for os control
* Added plot.cpp for plotting graphs
* Added csv.cpp to read csv files
* Added fileio.cpp for filehandling

Patch211 for Standard library development

---

Compiler/Compiletime/stack.py
Compiler/Parser/parser.py
Compiler/Parser/parserChecker.py
Compiler/Parser/parserTokenToNode.py
Core/Builtin/basic.h
Core/Runtime/memory.h

Csq was lacking name checks during parsing instead it did during runtime but now it can also be done at compiletime.

Introduced checking for undefined entities
